### ISSUE TITLE
Refactor the C++ version of unique_id so it can be included in more than one cpp file

### ISSUE THREAD

**Issue by corot** [ros-geographic-info/unique_identifier#7]
Just put "inline" on each function should do the trick, or (more tedious) separate the implementation in a cpp. Otherwise, it's a pain to use is in multiple source files.

Or am I missing the right use of it? In that case, please feel free to close this, and...  ideally give me a solution :pray:

**Comment by jack-oquin** [comment]
@corot: does the latest master using ``static inline`` fix your problem?

**Comment by jack-oquin** [comment]
Even without further test verification, I am releasing this to Indigo and Jade.

Do you need a Hydro release, too?

**Comment by jack-oquin** [comment]
Fixed for Indigo and Jade in release 1.0.5.

**Comment by corot** [comment]
Hi @jack-oquin, sorry for the delay. Works fine now, so I removed the wrapper. Thanks!

**Comment by jack-oquin** [comment]
Glad it fixes your problem. I released it to Indigo and Jade, but not Hydro.

Do you need a Hydro release for this?

**Comment by corot** [comment]
We use indigo, so no problem for us. I think you don't need to bother to release on hydro

**Comment by jack-oquin** [comment]
Sounds good. Since Hydro is near end-of-life I see no need to release it there.
